Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job                         count    min threads    max threads
------------------------  -------  -------------  -------------
all                             1              1              1
clean_subset_summary            2              1              1
clean_summary_document          1              1              1
compile_summary_document        2              1              1
create_dataset_summary          1              1              1
create_subset_document          2              1              1
create_subset_summary           2              1              1
total                          11              1              1

Select jobs to execute...

[Thu Jun  2 21:34:17 2022]
rule create_subset_summary:
    input: workflows/example_workflow/datasets/uniprot_ec_1_1_1_86_filtered_reviewed_yes/subsets/classI_kari/uniprot_ec_1_1_1_86_filtered_reviewed_yes_classI_kari.aln, workflows/example_workflow/datasets/uniprot_ec_1_1_1_86_filtered_reviewed_yes/subsets/classI_kari/csv/uniprot_ec_1_1_1_86_filtered_reviewed_yes_classI_kari_alignment.csv
    output: workflows/example_workflow/datasets/uniprot_ec_1_1_1_86_filtered_reviewed_yes/dataset_summary/uniprot_ec_1_1_1_86_filtered_reviewed_yes/subsets/classI_kari/temp/classI_kari_subset_summary.ipynb
    log: workflows/example_workflow/datasets/uniprot_ec_1_1_1_86_filtered_reviewed_yes/dataset_summary/uniprot_ec_1_1_1_86_filtered_reviewed_yes/subsets/classI_kari/temp/classI_kari_subset_summary.ipynb
    jobid: 20
    reason: Code has changed since last execution
    wildcards: dataset=uniprot_ec_1_1_1_86_filtered_reviewed_yes, subset=classI_kari
    resources: tmpdir=/var/folders/xs/24s9hwqd191f2x7rhdy6_ryc0000gr/T

[Thu Jun  2 21:34:20 2022]
Error in rule create_subset_summary:
    jobid: 20
    output: workflows/example_workflow/datasets/uniprot_ec_1_1_1_86_filtered_reviewed_yes/dataset_summary/uniprot_ec_1_1_1_86_filtered_reviewed_yes/subsets/classI_kari/temp/classI_kari_subset_summary.ipynb
    log: workflows/example_workflow/datasets/uniprot_ec_1_1_1_86_filtered_reviewed_yes/dataset_summary/uniprot_ec_1_1_1_86_filtered_reviewed_yes/subsets/classI_kari/temp/classI_kari_subset_summary.ipynb (check log file(s) for error message)

RuleException:
CalledProcessError in line 304 of /Users/uqgfoley/Documents/asr_curation_moved/asr_curation/Snakefile:
Command 'set -euo pipefail;  jupyter-nbconvert --log-level ERROR --execute --output /Users/uqgfoley/Documents/asr_curation_moved/asr_curation/workflows/example_workflow/datasets/uniprot_ec_1_1_1_86_filtered_reviewed_yes/dataset_summary/uniprot_ec_1_1_1_86_filtered_reviewed_yes/subsets/classI_kari/temp/classI_kari_subset_summary.ipynb --to notebook --ExecutePreprocessor.timeout=-1 /Users/uqgfoley/Documents/asr_curation_moved/asr_curation/.snakemake/scripts/tmpksiawxp0.create_subset_document.py.ipynb' returned non-zero exit status 1.
  File "/Users/uqgfoley/Documents/asr_curation_moved/asr_curation/Snakefile", line 304, in __rule_create_subset_summary
  File "/Users/uqgfoley/opt/miniconda3/envs/asr_curation241/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Removing output files of failed job create_subset_summary since they might be corrupted:
workflows/example_workflow/datasets/uniprot_ec_1_1_1_86_filtered_reviewed_yes/dataset_summary/uniprot_ec_1_1_1_86_filtered_reviewed_yes/subsets/classI_kari/temp/classI_kari_subset_summary.ipynb
Job failed, going on with independent jobs.
Select jobs to execute...

[Thu Jun  2 21:34:20 2022]
rule create_dataset_summary:
    input: workflows/example_workflow/datasets/uniprot_ec_1_1_1_86_filtered_reviewed_yes/csv/custom/uniprot_ec_1_1_1_86_filtered_reviewed_yes_annotated.csv
    output: workflows/example_workflow/datasets/uniprot_ec_1_1_1_86_filtered_reviewed_yes/dataset_summary/temp/uniprot_ec_1_1_1_86_filtered_reviewed_yes_summary.ipynb
    log: workflows/example_workflow/datasets/uniprot_ec_1_1_1_86_filtered_reviewed_yes/dataset_summary/temp/uniprot_ec_1_1_1_86_filtered_reviewed_yes_summary.ipynb
    jobid: 14
    reason: Code has changed since last execution
    wildcards: dataset=uniprot_ec_1_1_1_86_filtered_reviewed_yes
    resources: tmpdir=/var/folders/xs/24s9hwqd191f2x7rhdy6_ryc0000gr/T

[Thu Jun  2 21:34:23 2022]
Error in rule create_dataset_summary:
    jobid: 14
    output: workflows/example_workflow/datasets/uniprot_ec_1_1_1_86_filtered_reviewed_yes/dataset_summary/temp/uniprot_ec_1_1_1_86_filtered_reviewed_yes_summary.ipynb
    log: workflows/example_workflow/datasets/uniprot_ec_1_1_1_86_filtered_reviewed_yes/dataset_summary/temp/uniprot_ec_1_1_1_86_filtered_reviewed_yes_summary.ipynb (check log file(s) for error message)

RuleException:
CalledProcessError in line 281 of /Users/uqgfoley/Documents/asr_curation_moved/asr_curation/Snakefile:
Command 'set -euo pipefail;  jupyter-nbconvert --log-level ERROR --execute --output /Users/uqgfoley/Documents/asr_curation_moved/asr_curation/workflows/example_workflow/datasets/uniprot_ec_1_1_1_86_filtered_reviewed_yes/dataset_summary/temp/uniprot_ec_1_1_1_86_filtered_reviewed_yes_summary.ipynb --to notebook --ExecutePreprocessor.timeout=-1 /Users/uqgfoley/Documents/asr_curation_moved/asr_curation/.snakemake/scripts/tmpelkxv_rj.create_summary_document.py.ipynb' returned non-zero exit status 1.
  File "/Users/uqgfoley/Documents/asr_curation_moved/asr_curation/Snakefile", line 281, in __rule_create_dataset_summary
  File "/Users/uqgfoley/opt/miniconda3/envs/asr_curation241/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Removing output files of failed job create_dataset_summary since they might be corrupted:
workflows/example_workflow/datasets/uniprot_ec_1_1_1_86_filtered_reviewed_yes/dataset_summary/temp/uniprot_ec_1_1_1_86_filtered_reviewed_yes_summary.ipynb
Job failed, going on with independent jobs.
Select jobs to execute...

[Thu Jun  2 21:34:23 2022]
rule create_subset_summary:
    input: workflows/example_workflow/datasets/uniprot_ec_1_1_1_86_filtered_reviewed_yes/subsets/eukaryotic_kari/uniprot_ec_1_1_1_86_filtered_reviewed_yes_eukaryotic_kari.aln, workflows/example_workflow/datasets/uniprot_ec_1_1_1_86_filtered_reviewed_yes/subsets/eukaryotic_kari/csv/uniprot_ec_1_1_1_86_filtered_reviewed_yes_eukaryotic_kari_alignment.csv
    output: workflows/example_workflow/datasets/uniprot_ec_1_1_1_86_filtered_reviewed_yes/dataset_summary/uniprot_ec_1_1_1_86_filtered_reviewed_yes/subsets/eukaryotic_kari/temp/eukaryotic_kari_subset_summary.ipynb
    log: workflows/example_workflow/datasets/uniprot_ec_1_1_1_86_filtered_reviewed_yes/dataset_summary/uniprot_ec_1_1_1_86_filtered_reviewed_yes/subsets/eukaryotic_kari/temp/eukaryotic_kari_subset_summary.ipynb
    jobid: 16
    reason: Code has changed since last execution
    wildcards: dataset=uniprot_ec_1_1_1_86_filtered_reviewed_yes, subset=eukaryotic_kari
    resources: tmpdir=/var/folders/xs/24s9hwqd191f2x7rhdy6_ryc0000gr/T

[Thu Jun  2 21:34:26 2022]
Error in rule create_subset_summary:
    jobid: 16
    output: workflows/example_workflow/datasets/uniprot_ec_1_1_1_86_filtered_reviewed_yes/dataset_summary/uniprot_ec_1_1_1_86_filtered_reviewed_yes/subsets/eukaryotic_kari/temp/eukaryotic_kari_subset_summary.ipynb
    log: workflows/example_workflow/datasets/uniprot_ec_1_1_1_86_filtered_reviewed_yes/dataset_summary/uniprot_ec_1_1_1_86_filtered_reviewed_yes/subsets/eukaryotic_kari/temp/eukaryotic_kari_subset_summary.ipynb (check log file(s) for error message)

RuleException:
CalledProcessError in line 304 of /Users/uqgfoley/Documents/asr_curation_moved/asr_curation/Snakefile:
Command 'set -euo pipefail;  jupyter-nbconvert --log-level ERROR --execute --output /Users/uqgfoley/Documents/asr_curation_moved/asr_curation/workflows/example_workflow/datasets/uniprot_ec_1_1_1_86_filtered_reviewed_yes/dataset_summary/uniprot_ec_1_1_1_86_filtered_reviewed_yes/subsets/eukaryotic_kari/temp/eukaryotic_kari_subset_summary.ipynb --to notebook --ExecutePreprocessor.timeout=-1 /Users/uqgfoley/Documents/asr_curation_moved/asr_curation/.snakemake/scripts/tmpd6yo29_k.create_subset_document.py.ipynb' returned non-zero exit status 1.
  File "/Users/uqgfoley/Documents/asr_curation_moved/asr_curation/Snakefile", line 304, in __rule_create_subset_summary
  File "/Users/uqgfoley/opt/miniconda3/envs/asr_curation241/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Removing output files of failed job create_subset_summary since they might be corrupted:
workflows/example_workflow/datasets/uniprot_ec_1_1_1_86_filtered_reviewed_yes/dataset_summary/uniprot_ec_1_1_1_86_filtered_reviewed_yes/subsets/eukaryotic_kari/temp/eukaryotic_kari_subset_summary.ipynb
Job failed, going on with independent jobs.
Exiting because a job execution failed. Look above for error message
BUG: Out of jobs ready to be started, but not all files built yet. Please check https://github.com/snakemake/snakemake/issues/823 for more information.
Remaining jobs:
 - compile_summary_document: workflows/example_workflow/datasets/uniprot_ec_1_1_1_86_filtered_reviewed_yes/dataset_summary/eukaryotic_kari/_build/html/index.html
 - all: 
 - clean_summary_document: workflows/example_workflow/datasets/uniprot_ec_1_1_1_86_filtered_reviewed_yes/dataset_summary/uniprot_ec_1_1_1_86_filtered_reviewed_yes_summary_cleaned.ipynb
 - clean_subset_summary: workflows/example_workflow/datasets/uniprot_ec_1_1_1_86_filtered_reviewed_yes/dataset_summary/uniprot_ec_1_1_1_86_filtered_reviewed_yes/subsets/eukaryotic_kari/eukaryotic_kari_subset_summary_cleaned.ipynb
 - compile_summary_document: workflows/example_workflow/datasets/uniprot_ec_1_1_1_86_filtered_reviewed_yes/dataset_summary/classI_kari/_build/html/index.html
 - clean_subset_summary: workflows/example_workflow/datasets/uniprot_ec_1_1_1_86_filtered_reviewed_yes/dataset_summary/uniprot_ec_1_1_1_86_filtered_reviewed_yes/subsets/classI_kari/classI_kari_subset_summary_cleaned.ipynb
 - create_subset_document: workflows/example_workflow/datasets/uniprot_ec_1_1_1_86_filtered_reviewed_yes/dataset_summary/eukaryotic_kari/_config.yml, workflows/example_workflow/datasets/uniprot_ec_1_1_1_86_filtered_reviewed_yes/dataset_summary/eukaryotic_kari/_toc.yml
 - create_dataset_summary: workflows/example_workflow/datasets/uniprot_ec_1_1_1_86_filtered_reviewed_yes/dataset_summary/temp/uniprot_ec_1_1_1_86_filtered_reviewed_yes_summary.ipynb
 - create_subset_summary: workflows/example_workflow/datasets/uniprot_ec_1_1_1_86_filtered_reviewed_yes/dataset_summary/uniprot_ec_1_1_1_86_filtered_reviewed_yes/subsets/eukaryotic_kari/temp/eukaryotic_kari_subset_summary.ipynb
 - create_subset_document: workflows/example_workflow/datasets/uniprot_ec_1_1_1_86_filtered_reviewed_yes/dataset_summary/classI_kari/_config.yml, workflows/example_workflow/datasets/uniprot_ec_1_1_1_86_filtered_reviewed_yes/dataset_summary/classI_kari/_toc.yml
 - create_subset_summary: workflows/example_workflow/datasets/uniprot_ec_1_1_1_86_filtered_reviewed_yes/dataset_summary/uniprot_ec_1_1_1_86_filtered_reviewed_yes/subsets/classI_kari/temp/classI_kari_subset_summary.ipynb
Complete log: .snakemake/log/2022-06-02T213416.912629.snakemake.log
